In [34]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [35]:
df1=pd.read_csv("diabetes-1.csv")

In [36]:
df1.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [37]:
df1.shape

(768, 9)

In [38]:
df2=df1.drop(["Pregnancies","DiabetesPedigreeFunction"],axis="columns")

In [39]:
df2

Glucose  BloodPressure  SkinThickness  Insulin   BMI  Age  Outcome
0        148             72             35        0  33.6   50        1
1         85             66             29        0  26.6   31        0
2        183             64              0        0  23.3   32        1
3         89             66             23       94  28.1   21        0
4        137             40             35      168  43.1   33        1
..       ...            ...            ...      ...   ...  ...      ...
763      101             76             48      180  32.9   63        0
764      122             70             27        0  36.8   27        0
765      121             72             23      112  26.2   30        0
766      126             60              0        0  30.1   47        1
767       93             70             31        0  30.4   23        0

[768 rows x 7 columns]

In [40]:
df2.isnull().sum()

Glucose          0
BloodPressure    0
SkinThickness    0
Insulin          0
BMI              0
Age              0
Outcome          0
dtype: int64

In [41]:
df2.Outcome.unique()

array([1, 0], dtype=int64)

In [42]:
df2.Age.unique()

array([50, 31, 32, 21, 33, 30, 26, 29, 53, 54, 34, 57, 59, 51, 27, 41, 43,
       22, 38, 60, 28, 45, 35, 46, 56, 37, 48, 40, 25, 24, 58, 42, 44, 39,
       36, 23, 61, 69, 62, 55, 65, 47, 52, 66, 49, 63, 67, 72, 81, 64, 70,
       68], dtype=int64)

In [43]:
df2.describe()


Glucose  BloodPressure  SkinThickness     Insulin         BMI  \
count  768.000000     768.000000     768.000000  768.000000  768.000000   
mean   120.894531      69.105469      20.536458   79.799479   31.992578   
std     31.972618      19.355807      15.952218  115.244002    7.884160   
min      0.000000       0.000000       0.000000    0.000000    0.000000   
25%     99.000000      62.000000       0.000000    0.000000   27.300000   
50%    117.000000      72.000000      23.000000   30.500000   32.000000   
75%    140.250000      80.000000      32.000000  127.250000   36.600000   
max    199.000000     122.000000      99.000000  846.000000   67.100000   

              Age     Outcome  
count  768.000000  768.000000  
mean    33.240885    0.348958  
std     11.760232    0.476951  
min     21.000000    0.000000  
25%     24.000000    0.000000  
50%     29.000000    0.000000  
75%     41.000000    1.000000  
max     81.000000    1.000000

In [52]:
#df2=df2.mask(df2==0).fillna(df2.mean())

df2["Glucose"] = df2["Glucose"].replace(0,120.89453125)
df2["BloodPressure"] = df2["BloodPressure"].replace(0,69.10546875)
df2["SkinThickness"] = df2["SkinThickness"].replace(0,20.536458333333332)
df2["Insulin"] = df2["Insulin"].replace(0,79.79947916666667)
df2["BMI"] = df2["BMI"].replace(0,31.992578124999998)
df2["Age"] = df2["Age"].replace(0,33.240885416666664)


df2

Glucose  BloodPressure  SkinThickness     Insulin   BMI  Age  Outcome
0      148.0           72.0      35.000000   79.799479  33.6   50        1
1       85.0           66.0      29.000000   79.799479  26.6   31        0
2      183.0           64.0      20.536458   79.799479  23.3   32        1
3       89.0           66.0      23.000000   94.000000  28.1   21        0
4      137.0           40.0      35.000000  168.000000  43.1   33        1
..       ...            ...            ...         ...   ...  ...      ...
763    101.0           76.0      48.000000  180.000000  32.9   63        0
764    122.0           70.0      27.000000   79.799479  36.8   27        0
765    121.0           72.0      23.000000  112.000000  26.2   30        0
766    126.0           60.0      20.536458   79.799479  30.1   47        1
767     93.0           70.0      31.000000   79.799479  30.4   23        0

[768 rows x 7 columns]

In [53]:
from sklearn.model_selection import train_test_split
x = np.asarray(df2[["Glucose","BloodPressure","SkinThickness","Insulin","BMI","Age"]])
y = np.asarray(df2["Outcome"])
x_train, x_test, y_train, y_test = train_test_split( x, y, test_size=0.2, random_state=4)

print ('Train set:', x_train.shape,  y_train.shape)
print ('Test set:', x_test.shape,  y_test.shape)

Train set: (614, 6) (614,)
Test set: (154, 6) (154,)


In [54]:
print("# Total no. of Rows {0}".format(len(df2)))
print("# Rows missing Glucose Values {0}".format(len(df2.loc[df2.Glucose==0])))
print("# Rows missing BloodPressure Values {0}".format(len(df2.loc[df2.BloodPressure==0])))
print("# Rows missing Skin Thickness Values {0}".format(len(df2.loc[df2.SkinThickness==0])))
print("# Rows missing Insulin Values {0}".format(len(df2.loc[df2.Insulin==0])))
print("# Rows missing BMI Values {0}".format(len(df2.loc[df2.BMI==0])))
print("# Rows missing Age Values {0}".format(len(df2.loc[df2.Glucose==0])))


# Total no. of Rows 768
# Rows missing Glucose Values 0
# Rows missing BloodPressure Values 0
# Rows missing Skin Thickness Values 0
# Rows missing Insulin Values 0
# Rows missing BMI Values 0
# Rows missing Age Values 0


In [55]:
# from sklearn.impute import SimpleImputer
# fill_0 = SimpleImputer(missing_values=0, strategy="mean")

# x_train = fill_0.fit_transform(x_train)
# x_test = fill_0.fit_transform(x_test)
#df2.Glucose.mean()
#df2["Glucose"]=df2["Glucose"].replace(0,120.89453125)
# df2=df2.mask(df2==0).fillna(df2.mean())


In [56]:
print("# Total no. of Rows {0}".format(len(df2)))
print("# Rows missing Glucose Values {0}".format(len(df2.loc[df2.Glucose==0])))
print("# Rows missing BloodPressure Values {0}".format(len(df2.loc[df2.BloodPressure==0])))
print("# Rows missing Skin Thickness Values {0}".format(len(df2.loc[df2.SkinThickness==0])))
print("# Rows missing Insulin Values {0}".format(len(df2.loc[df2.Insulin==0])))
print("# Rows missing BMI Values {0}".format(len(df2.loc[df2.BMI==0])))
print("# Rows missing Age Values {0}".format(len(df2.loc[df2.Glucose==0])))

# Total no. of Rows 768
# Rows missing Glucose Values 0
# Rows missing BloodPressure Values 0
# Rows missing Skin Thickness Values 0
# Rows missing Insulin Values 0
# Rows missing BMI Values 0
# Rows missing Age Values 0


In [70]:
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import confusion_matrix
LR = LogisticRegression(C=0.01, solver='lbfgs').fit(x_train,y_train)
LR

LogisticRegression(C=0.01, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=None, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [71]:
yhat=LR.predict(x_test)
yhat

array([0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0,
       1, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1],
      dtype=int64)

In [72]:
from sklearn.metrics import jaccard_similarity_score
jaccard_similarity_score(y_test, yhat)

C:\Users\lenovo\AppData\Local\Programs\Python\Python37\lib\site-packages\sklearn\metrics\_classification.py:664: FutureWarning: jaccard_similarity_score has been deprecated and replaced with jaccard_score. It will be removed in version 0.23. This implementation has surprising behavior for binary and multiclass classification tasks.
  FutureWarning)


0.8051948051948052

In [73]:
print(confusion_matrix(y_test, yhat, labels=[1,0]))

[[37 15]
 [15 87]]


In [74]:
yhat_prob = LR.predict_proba(x_test)
yhat_prob

array([[0.77624558, 0.22375442],
       [0.93677987, 0.06322013],
       [0.89111212, 0.10888788],
       [0.51369484, 0.48630516],
       [0.67085644, 0.32914356],
       [0.37583817, 0.62416183],
       [0.34374398, 0.65625602],
       [0.87807418, 0.12192582],
       [0.22187583, 0.77812417],
       [0.90456537, 0.09543463],
       [0.42985033, 0.57014967],
       [0.91445769, 0.08554231],
       [0.76234389, 0.23765611],
       [0.93755417, 0.06244583],
       [0.87504674, 0.12495326],
       [0.46728993, 0.53271007],
       [0.11744348, 0.88255652],
       [0.07764947, 0.92235053],
       [0.96694753, 0.03305247],
       [0.94287509, 0.05712491],
       [0.90600745, 0.09399255],
       [0.40148234, 0.59851766],
       [0.86217514, 0.13782486],
       [0.12551328, 0.87448672],
       [0.87464504, 0.12535496],
       [0.4894671 , 0.5105329 ],
       [0.92080276, 0.07919724],
       [0.64403757, 0.35596243],
       [0.6835253 , 0.3164747 ],
       [0.84419422, 0.15580578],
       [0.

In [115]:
# Glucose, BloodPressure, SkinThickness, Insulin, BMI, Age
pred=[148.0,72.0,35.000000,79.799479,33.6,50]
Diab_pred=LR.predict_proba([pred])[0][1]*100

In [120]:
print("Probability of Diabetes : ""{0:.2f} %".format(Diab_pred))

Probability of Diabetes : 70.68 %
